#!/usr/bin/env bash
# Script to fetch A record details for the domain shammah.tech and its subdomains.

# Function to display A record info
get_a_record() {
    local domain="shammah.tech"
    local subdomain=$1
    local full_domain="$subdomain.$domain"

    local record_info=$(dig +short -t A "$full_domain")

    # Check if record_info has data, i.e., the subdomain exists
    if [[ $record_info ]]; then
        echo "The subdomain $subdomain is a A record and points to $record_info"
    else
        echo "No A record found for $full_domain"
    fi
}

# Check if subdomain argument is provided
if [ -z "$1" ]; then
    for subdomain in www lb-01 web-01 web-02; do
        get_a_record "$subdomain"
    done
else
    # If subdomain argument is provided
    subdomain=$1
    get_a_record "$subdomain"
fi
