#!/usr/bin/env bash
# Accepts a string as an argument and displays a message if the argument is not passed.

# Check if the script is given an argument
if [ $# -eq 0 ]; then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
    
# Function to ping the IP address 5 times
else
# Call the function with the provided IP address argument
  ping -c 5 "$1"
fi
