#!/usr/bin/env bash
# This script fixes the issue causing Nginx to not run on port 80.

# Remove the default configuration file from sites-enabled.
rm /etc/nginx/sites-enabled/default

# Create a symbolic link from sites-available to sites-enabled.
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# Restart the Nginx service to apply the configuration changes.
service nginx restart
