#!/usr/bin/env bash
# A script to display "Infinity and beyond" indefinitely with a sleep 2 between each iteration
# Show "I am invincible!!!" when receiving a SIGTERM signal

while true
do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo "I am invincible"' SIGTERM 
done

# # Function to handle the SIGTERM signal
# function handle_sigterm {
#     echo "I am invincible!!!"
#     exit 0
# }

# # Trap the SIGTERM signal and call the function
# trap handle_sigterm SIGTERM

# # Infinite loop with sleep of 2 seconds
# while true
# do
#     echo "To infinity and beyond"
#     sleep 2
# done