#!/usr/bin/env bash
# This script displays the content of the /etc/passwd file with the specified format.

file="/etc/passwd"

# Check if the file exists
if [ -f "$file" ]; then
    # Read the file line by line using while loop and IFS as ':'
    while IFS=: read -r username _ userid groupid _ _ homedir shell
    do
        echo "The user $username is part of the group $groupid gang,"
        echo "lives in $homedir and rides $shell."
        echo "User ID's place is protected by the passcode PASSWORD,"
        echo "more info about the user here: USER ID INFO"
        echo
    done < "$file"
else
    echo "Error: /etc/passwd file does not exist."
fi
