#!/usr/bin/env bash
#Script that displays "Best School" 10 times, with "Hi" on a new line in the 9th iteration

counter=1

while [ $counter -le 10 ]
do
    if [ $counter -eq 9 ]
    then
        echo "Best School"
        echo "Hi"
    else
        echo "Best School"
    fi
    
    ((counter++))
done
