#!/usr/bin/env bash
# This script displays the content of the current directory in a list format,
# showing only the part of the name after the first dash.

for file in *
do
    # Check if the file is not a hidden file (doesn't start with a dot)
    if [[ ! $file =~ ^\..* ]]; then
        # Extract the part of the name after the first dash
        name=$(echo "$file" | cut -d'-' -f2-)
        echo "$name"
    fi
done
