#!/usr/bin/env bash
# Configures an Ubuntu Server as follows:
# - localhost resolves to 127.0.0.2
# - facebook.com resolves to 8.8.8.8

# Check if the script is running inside Docker
cp /etc/hosts ~/hosts.new
echo "127.0.0.2		localhost" > ~/hosts.new
#Resolves to facebook.com
echo "8.8.8.8		facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
