#!/usr/bin/env bash
# Script displays all active IPv4 IPs on the machine it’s executed on.

#ip -4 addr show | grep -oP '(?<=inet\s)\d+(\.\d+){3}'
ifconfig | grep -Eo "inet (addr:)?([0-9]*\.){3}[0-9]*" | cut -b 11-
