#!/usr/bin/env bash
# This script configures Nginx to run as 'nginx' user and listen on port 8080.

# Update Nginx to run as 'nginx' user
sed -i 's/user .*/user nginx;/' /etc/nginx/nginx.conf

# Update Nginx to listen on port 8080
sed -i 's/listen .*/listen 8080;/' /etc/nginx/sites-available/default

# Restart Nginx
service nginx restart
